"""Utilities for solving 1D and 2D Fisher-KPP equations with RK4."""

from .solver import (
    apply_dirichlet_bc,
    apply_dirichlet_bc_2d_from_exact,
    apply_neumann_bc_2d,
    area_fraction_2d,
    backward_euler_step,
    check_forward_euler_stability,
    check_rk4_stability,
    estimate_front_speed,
    fisher_kpp_rhs,
    fisher_kpp_rhs_2d,
    forward_euler_step,
    front_position,
    long_time_curve_exact,
    mean_mass,
    relative_l2,
    rk4_step,
    rk4_step_2d,
    rk4_step_2d_dirichlet_exact,
    solve_1d_method,
    solve_long_time_curve,
    solve_rk4,
    solve_rk4_2d,
    trapezoidal_step,
)

__all__ = [
    "apply_dirichlet_bc",
    "apply_dirichlet_bc_2d_from_exact",
    "apply_neumann_bc_2d",
    "area_fraction_2d",
    "backward_euler_step",
    "check_forward_euler_stability",
    "check_rk4_stability",
    "estimate_front_speed",
    "fisher_kpp_rhs",
    "fisher_kpp_rhs_2d",
    "forward_euler_step",
    "front_position",
    "long_time_curve_exact",
    "mean_mass",
    "relative_l2",
    "rk4_step",
    "rk4_step_2d",
    "rk4_step_2d_dirichlet_exact",
    "solve_1d_method",
    "solve_long_time_curve",
    "solve_rk4",
    "solve_rk4_2d",
    "trapezoidal_step",
]
